- name: "Install Docker" 
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes